//
// ActivitiesBody.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ActivitiesBody: Codable {

    /** The name of the activity. */
    public var name: String
    /** Type of activity. For example - Run, Ride etc. */
    public var type: String?
    /** Sport type of activity. For example - Run, MountainBikeRide, Ride, etc. */
    public var sportType: String
    /** ISO 8601 formatted date time. */
    public var startDateLocal: Date
    /** In seconds. */
    public var elapsedTime: Int
    /** Description of the activity. */
    public var _description: String?
    /** In meters. */
    public var distance: Float?
    /** Set to 1 to mark as a trainer activity. */
    public var trainer: Int?
    /** Set to 1 to mark as commute. */
    public var commute: Int?

    public init(name: String, type: String? = nil, sportType: String, startDateLocal: Date, elapsedTime: Int, _description: String? = nil, distance: Float? = nil, trainer: Int? = nil, commute: Int? = nil) {
        self.name = name
        self.type = type
        self.sportType = sportType
        self.startDateLocal = startDateLocal
        self.elapsedTime = elapsedTime
        self._description = _description
        self.distance = distance
        self.trainer = trainer
        self.commute = commute
    }

    public enum CodingKeys: String, CodingKey { 
        case name
        case type
        case sportType = "sport_type"
        case startDateLocal = "start_date_local"
        case elapsedTime = "elapsed_time"
        case _description = "description"
        case distance
        case trainer
        case commute
    }

}
