//
// ActivityStats.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** A set of rolled-up statistics and totals for an athlete */

public struct ActivityStats: Codable {

    /** The longest distance ridden by the athlete. */
    public var biggestRideDistance: Double?
    /** The highest climb ridden by the athlete. */
    public var biggestClimbElevationGain: Double?
    public var recentRideTotals: ActivityTotal?
    public var recentRunTotals: ActivityTotal?
    public var recentSwimTotals: ActivityTotal?
    public var ytdRideTotals: ActivityTotal?
    public var ytdRunTotals: ActivityTotal?
    public var ytdSwimTotals: ActivityTotal?
    public var allRideTotals: ActivityTotal?
    public var allRunTotals: ActivityTotal?
    public var allSwimTotals: ActivityTotal?

    public init(biggestRideDistance: Double? = nil, biggestClimbElevationGain: Double? = nil, recentRideTotals: ActivityTotal? = nil, recentRunTotals: ActivityTotal? = nil, recentSwimTotals: ActivityTotal? = nil, ytdRideTotals: ActivityTotal? = nil, ytdRunTotals: ActivityTotal? = nil, ytdSwimTotals: ActivityTotal? = nil, allRideTotals: ActivityTotal? = nil, allRunTotals: ActivityTotal? = nil, allSwimTotals: ActivityTotal? = nil) {
        self.biggestRideDistance = biggestRideDistance
        self.biggestClimbElevationGain = biggestClimbElevationGain
        self.recentRideTotals = recentRideTotals
        self.recentRunTotals = recentRunTotals
        self.recentSwimTotals = recentSwimTotals
        self.ytdRideTotals = ytdRideTotals
        self.ytdRunTotals = ytdRunTotals
        self.ytdSwimTotals = ytdSwimTotals
        self.allRideTotals = allRideTotals
        self.allRunTotals = allRunTotals
        self.allSwimTotals = allSwimTotals
    }

    public enum CodingKeys: String, CodingKey { 
        case biggestRideDistance = "biggest_ride_distance"
        case biggestClimbElevationGain = "biggest_climb_elevation_gain"
        case recentRideTotals = "recent_ride_totals"
        case recentRunTotals = "recent_run_totals"
        case recentSwimTotals = "recent_swim_totals"
        case ytdRideTotals = "ytd_ride_totals"
        case ytdRunTotals = "ytd_run_totals"
        case ytdSwimTotals = "ytd_swim_totals"
        case allRideTotals = "all_ride_totals"
        case allRunTotals = "all_run_totals"
        case allSwimTotals = "all_swim_totals"
    }

}
