//
// Comment.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Comment: Codable {

    /** The unique identifier of this comment */
    public var _id: Int64?
    /** The identifier of the activity this comment is related to */
    public var activityId: Int64?
    /** The content of the comment */
    public var text: String?
    public var athlete: SummaryAthlete?
    /** The time at which this comment was created. */
    public var createdAt: Date?

    public init(_id: Int64? = nil, activityId: Int64? = nil, text: String? = nil, athlete: SummaryAthlete? = nil, createdAt: Date? = nil) {
        self._id = _id
        self.activityId = activityId
        self.text = text
        self.athlete = athlete
        self.createdAt = createdAt
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case activityId = "activity_id"
        case text
        case athlete
        case createdAt = "created_at"
    }

}
