//
// DetailedSegmentEffort.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct DetailedSegmentEffort: Codable {

    /** The unique identifier of this effort */
    public var _id: Int64?
    /** The unique identifier of the activity related to this effort */
    public var activityId: Int64?
    /** The effort&#x27;s elapsed time */
    public var elapsedTime: Int?
    /** The time at which the effort was started. */
    public var startDate: Date?
    /** The time at which the effort was started in the local timezone. */
    public var startDateLocal: Date?
    /** The effort&#x27;s distance in meters */
    public var distance: Float?
    /** Whether this effort is the current best on the leaderboard */
    public var isKom: Bool?
    /** The name of the segment on which this effort was performed */
    public var name: String?
    public var activity: MetaActivity?
    public var athlete: MetaAthlete?
    /** The effort&#x27;s moving time */
    public var movingTime: Int?
    /** The start index of this effort in its activity&#x27;s stream */
    public var startIndex: Int?
    /** The end index of this effort in its activity&#x27;s stream */
    public var endIndex: Int?
    /** The effort&#x27;s average cadence */
    public var averageCadence: Float?
    /** The average wattage of this effort */
    public var averageWatts: Float?
    /** For riding efforts, whether the wattage was reported by a dedicated recording device */
    public var deviceWatts: Bool?
    /** The heart heart rate of the athlete during this effort */
    public var averageHeartrate: Float?
    /** The maximum heart rate of the athlete during this effort */
    public var maxHeartrate: Float?
    public var segment: SummarySegment?
    /** The rank of the effort on the global leaderboard if it belongs in the top 10 at the time of upload */
    public var komRank: Int?
    /** The rank of the effort on the athlete&#x27;s leaderboard if it belongs in the top 3 at the time of upload */
    public var prRank: Int?
    /** Whether this effort should be hidden when viewed within an activity */
    public var hidden: Bool?

    public init(_id: Int64? = nil, activityId: Int64? = nil, elapsedTime: Int? = nil, startDate: Date? = nil, startDateLocal: Date? = nil, distance: Float? = nil, isKom: Bool? = nil, name: String? = nil, activity: MetaActivity? = nil, athlete: MetaAthlete? = nil, movingTime: Int? = nil, startIndex: Int? = nil, endIndex: Int? = nil, averageCadence: Float? = nil, averageWatts: Float? = nil, deviceWatts: Bool? = nil, averageHeartrate: Float? = nil, maxHeartrate: Float? = nil, segment: SummarySegment? = nil, komRank: Int? = nil, prRank: Int? = nil, hidden: Bool? = nil) {
        self._id = _id
        self.activityId = activityId
        self.elapsedTime = elapsedTime
        self.startDate = startDate
        self.startDateLocal = startDateLocal
        self.distance = distance
        self.isKom = isKom
        self.name = name
        self.activity = activity
        self.athlete = athlete
        self.movingTime = movingTime
        self.startIndex = startIndex
        self.endIndex = endIndex
        self.averageCadence = averageCadence
        self.averageWatts = averageWatts
        self.deviceWatts = deviceWatts
        self.averageHeartrate = averageHeartrate
        self.maxHeartrate = maxHeartrate
        self.segment = segment
        self.komRank = komRank
        self.prRank = prRank
        self.hidden = hidden
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case activityId = "activity_id"
        case elapsedTime = "elapsed_time"
        case startDate = "start_date"
        case startDateLocal = "start_date_local"
        case distance
        case isKom = "is_kom"
        case name
        case activity
        case athlete
        case movingTime = "moving_time"
        case startIndex = "start_index"
        case endIndex = "end_index"
        case averageCadence = "average_cadence"
        case averageWatts = "average_watts"
        case deviceWatts = "device_watts"
        case averageHeartrate = "average_heartrate"
        case maxHeartrate = "max_heartrate"
        case segment
        case komRank = "kom_rank"
        case prRank = "pr_rank"
        case hidden
    }

}
