//
// DetailedActivity.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct DetailedActivity: Codable {

    /** The description of the activity */
    public var _description: String?
    public var photos: PhotosSummary?
    public var gear: SummaryGear?
    /** The number of kilocalories consumed during this activity */
    public var calories: Float?
    public var segmentEfforts: [DetailedSegmentEffort]?
    /** The name of the device used to record the activity */
    public var deviceName: String?
    /** The token used to embed a Strava activity */
    public var embedToken: String?
    /** The splits of this activity in metric units (for runs) */
    public var splitsMetric: [Split]?
    /** The splits of this activity in imperial units (for runs) */
    public var splitsStandard: [Split]?
    public var laps: [Lap]?
    public var bestEfforts: [DetailedSegmentEffort]?

    public init(_description: String? = nil, photos: PhotosSummary? = nil, gear: SummaryGear? = nil, calories: Float? = nil, segmentEfforts: [DetailedSegmentEffort]? = nil, deviceName: String? = nil, embedToken: String? = nil, splitsMetric: [Split]? = nil, splitsStandard: [Split]? = nil, laps: [Lap]? = nil, bestEfforts: [DetailedSegmentEffort]? = nil) {
        self._description = _description
        self.photos = photos
        self.gear = gear
        self.calories = calories
        self.segmentEfforts = segmentEfforts
        self.deviceName = deviceName
        self.embedToken = embedToken
        self.splitsMetric = splitsMetric
        self.splitsStandard = splitsStandard
        self.laps = laps
        self.bestEfforts = bestEfforts
    }

    public enum CodingKeys: String, CodingKey { 
        case _description = "description"
        case photos
        case gear
        case calories
        case segmentEfforts = "segment_efforts"
        case deviceName = "device_name"
        case embedToken = "embed_token"
        case splitsMetric = "splits_metric"
        case splitsStandard = "splits_standard"
        case laps
        case bestEfforts = "best_efforts"
    }

}
