//
// DetailedGear.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct DetailedGear: Codable {

    /** The gear&#x27;s unique identifier. */
    public var _id: String?
    /** Resource state, indicates level of detail. Possible values: 2 -&gt; \&quot;summary\&quot;, 3 -&gt; \&quot;detail\&quot; */
    public var resourceState: Int?
    /** Whether this gear&#x27;s is the owner&#x27;s default one. */
    public var primary: Bool?
    /** The gear&#x27;s name. */
    public var name: String?
    /** The distance logged with this gear. */
    public var distance: Float?
    /** The gear&#x27;s brand name. */
    public var brandName: String?
    /** The gear&#x27;s model name. */
    public var modelName: String?
    /** The gear&#x27;s frame type (bike only). */
    public var frameType: Int?
    /** The gear&#x27;s description. */
    public var _description: String?

    public init(_id: String? = nil, resourceState: Int? = nil, primary: Bool? = nil, name: String? = nil, distance: Float? = nil, brandName: String? = nil, modelName: String? = nil, frameType: Int? = nil, _description: String? = nil) {
        self._id = _id
        self.resourceState = resourceState
        self.primary = primary
        self.name = name
        self.distance = distance
        self.brandName = brandName
        self.modelName = modelName
        self.frameType = frameType
        self._description = _description
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case resourceState = "resource_state"
        case primary
        case name
        case distance
        case brandName = "brand_name"
        case modelName = "model_name"
        case frameType = "frame_type"
        case _description = "description"
    }

}
