//
// Fault.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Encapsulates the errors that may be returned from the API. */

public struct Fault: Codable {

    /** The set of specific errors associated with this fault, if any. */
    public var errors: [ModelError]?
    /** The message of the fault. */
    public var message: String?

    public init(errors: [ModelError]? = nil, message: String? = nil) {
        self.errors = errors
        self.message = message
    }


}
