//
// HeartRateZoneRanges.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct HeartRateZoneRanges: Codable {

    /** Whether the athlete has set their own custom heart rate zones */
    public var customZones: Bool?
    public var zones: ZoneRanges?

    public init(customZones: Bool? = nil, zones: ZoneRanges? = nil) {
        self.customZones = customZones
        self.zones = zones
    }

    public enum CodingKeys: String, CodingKey { 
        case customZones = "custom_zones"
        case zones
    }

}
