//
// IdStarredBody.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct IdStarredBody: Codable {

    /** If true, star the segment; if false, unstar the segment. */
    public var starred: Bool

    public init(starred: Bool) {
        self.starred = starred
    }


}
