//
// LatLng.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** A pair of latitude/longitude coordinates, represented as an array of 2 floating point numbers. */
public typealias LatLng = [Float]