//
// MetaClub.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct MetaClub: Codable {

    /** The club&#x27;s unique identifier. */
    public var _id: Int64?
    /** Resource state, indicates level of detail. Possible values: 1 -&gt; \&quot;meta\&quot;, 2 -&gt; \&quot;summary\&quot;, 3 -&gt; \&quot;detail\&quot; */
    public var resourceState: Int?
    /** The club&#x27;s name. */
    public var name: String?

    public init(_id: Int64? = nil, resourceState: Int? = nil, name: String? = nil) {
        self._id = _id
        self.resourceState = resourceState
        self.name = name
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case resourceState = "resource_state"
        case name
    }

}
