//
// ModelError.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ModelError: Codable {

    /** The code associated with this error. */
    public var code: String?
    /** The specific field or aspect of the resource associated with this error. */
    public var field: String?
    /** The type of resource associated with this error. */
    public var resource: String?

    public init(code: String? = nil, field: String? = nil, resource: String? = nil) {
        self.code = code
        self.field = field
        self.resource = resource
    }


}
