//
// PhotosSummary.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PhotosSummary: Codable {

    /** The number of photos */
    public var count: Int?
    public var primary: PhotosSummaryPrimary?

    public init(count: Int? = nil, primary: PhotosSummaryPrimary? = nil) {
        self.count = count
        self.primary = primary
    }


}
