//
// PhotosSummaryPrimary.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PhotosSummaryPrimary: Codable {

    public var _id: Int64?
    public var source: Int?
    public var uniqueId: String?
    public var urls: [String:String]?

    public init(_id: Int64? = nil, source: Int? = nil, uniqueId: String? = nil, urls: [String:String]? = nil) {
        self._id = _id
        self.source = source
        self.uniqueId = uniqueId
        self.urls = urls
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case source
        case uniqueId = "unique_id"
        case urls
    }

}
