//
// PolylineMap.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PolylineMap: Codable {

    /** The identifier of the map */
    public var _id: String?
    /** The polyline of the map, only returned on detailed representation of an object */
    public var polyline: String?
    /** The summary polyline of the map */
    public var summaryPolyline: String?

    public init(_id: String? = nil, polyline: String? = nil, summaryPolyline: String? = nil) {
        self._id = _id
        self.polyline = polyline
        self.summaryPolyline = summaryPolyline
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case polyline
        case summaryPolyline = "summary_polyline"
    }

}
