//
// PowerStream.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PowerStream: Codable {

    public enum Resolution: String, Codable { 
        case low = "low"
        case medium = "medium"
        case high = "high"
    }
    public enum SeriesType: String, Codable { 
        case distance = "distance"
        case time = "time"
    }
    /** The number of data points in this stream */
    public var originalSize: Int?
    /** The level of detail (sampling) in which this stream was returned */
    public var resolution: Resolution?
    /** The base series used in the case the stream was downsampled */
    public var seriesType: SeriesType?
    /** The sequence of power values for this stream, in watts */
    public var data: [Int]?

    public init(originalSize: Int? = nil, resolution: Resolution? = nil, seriesType: SeriesType? = nil, data: [Int]? = nil) {
        self.originalSize = originalSize
        self.resolution = resolution
        self.seriesType = seriesType
        self.data = data
    }

    public enum CodingKeys: String, CodingKey { 
        case originalSize = "original_size"
        case resolution
        case seriesType = "series_type"
        case data
    }

}
