//
// PowerZoneRanges.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PowerZoneRanges: Codable {

    public var zones: ZoneRanges?

    public init(zones: ZoneRanges? = nil) {
        self.zones = zones
    }


}
