//
// Route.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Route: Codable {

    public var athlete: SummaryAthlete?
    /** The description of the route */
    public var _description: String?
    /** The route&#x27;s distance, in meters */
    public var distance: Float?
    /** The route&#x27;s elevation gain. */
    public var elevationGain: Float?
    /** The unique identifier of this route */
    public var _id: Int64?
    /** The unique identifier of the route in string format */
    public var idStr: String?
    public var map: PolylineMap?
    /** The name of this route */
    public var name: String?
    /** Whether this route is private */
    public var _private: Bool?
    /** Whether this route is starred by the logged-in athlete */
    public var starred: Bool?
    /** An epoch timestamp of when the route was created */
    public var timestamp: Int?
    /** This route&#x27;s type (1 for ride, 2 for runs) */
    public var type: Int?
    /** This route&#x27;s sub-type (1 for road, 2 for mountain bike, 3 for cross, 4 for trail, 5 for mixed) */
    public var subType: Int?
    /** The time at which the route was created */
    public var createdAt: Date?
    /** The time at which the route was last updated */
    public var updatedAt: Date?
    /** Estimated time in seconds for the authenticated athlete to complete route */
    public var estimatedMovingTime: Int?
    /** The segments traversed by this route */
    public var segments: [SummarySegment]?

    public init(athlete: SummaryAthlete? = nil, _description: String? = nil, distance: Float? = nil, elevationGain: Float? = nil, _id: Int64? = nil, idStr: String? = nil, map: PolylineMap? = nil, name: String? = nil, _private: Bool? = nil, starred: Bool? = nil, timestamp: Int? = nil, type: Int? = nil, subType: Int? = nil, createdAt: Date? = nil, updatedAt: Date? = nil, estimatedMovingTime: Int? = nil, segments: [SummarySegment]? = nil) {
        self.athlete = athlete
        self._description = _description
        self.distance = distance
        self.elevationGain = elevationGain
        self._id = _id
        self.idStr = idStr
        self.map = map
        self.name = name
        self._private = _private
        self.starred = starred
        self.timestamp = timestamp
        self.type = type
        self.subType = subType
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.estimatedMovingTime = estimatedMovingTime
        self.segments = segments
    }

    public enum CodingKeys: String, CodingKey { 
        case athlete
        case _description = "description"
        case distance
        case elevationGain = "elevation_gain"
        case _id = "id"
        case idStr = "id_str"
        case map
        case name
        case _private = "private"
        case starred
        case timestamp
        case type
        case subType = "sub_type"
        case createdAt = "created_at"
        case updatedAt = "updated_at"
        case estimatedMovingTime = "estimated_moving_time"
        case segments
    }

}
