//
// Split.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Split: Codable {

    /** The average speed of this split, in meters per second */
    public var averageSpeed: Float?
    /** The distance of this split, in meters */
    public var distance: Float?
    /** The elapsed time of this split, in seconds */
    public var elapsedTime: Int?
    /** The elevation difference of this split, in meters */
    public var elevationDifference: Float?
    /** The pacing zone of this split */
    public var paceZone: Int?
    /** The moving time of this split, in seconds */
    public var movingTime: Int?
    /** N/A */
    public var split: Int?

    public init(averageSpeed: Float? = nil, distance: Float? = nil, elapsedTime: Int? = nil, elevationDifference: Float? = nil, paceZone: Int? = nil, movingTime: Int? = nil, split: Int? = nil) {
        self.averageSpeed = averageSpeed
        self.distance = distance
        self.elapsedTime = elapsedTime
        self.elevationDifference = elevationDifference
        self.paceZone = paceZone
        self.movingTime = movingTime
        self.split = split
    }

    public enum CodingKeys: String, CodingKey { 
        case averageSpeed = "average_speed"
        case distance
        case elapsedTime = "elapsed_time"
        case elevationDifference = "elevation_difference"
        case paceZone = "pace_zone"
        case movingTime = "moving_time"
        case split
    }

}
