//
// StreamSet.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct StreamSet: Codable {

    public var time: TimeStream?
    public var distance: DistanceStream?
    public var latlng: LatLngStream?
    public var altitude: AltitudeStream?
    public var velocitySmooth: SmoothVelocityStream?
    public var heartrate: HeartrateStream?
    public var cadence: CadenceStream?
    public var watts: PowerStream?
    public var temp: TemperatureStream?
    public var moving: MovingStream?
    public var gradeSmooth: SmoothGradeStream?

    public init(time: TimeStream? = nil, distance: DistanceStream? = nil, latlng: LatLngStream? = nil, altitude: AltitudeStream? = nil, velocitySmooth: SmoothVelocityStream? = nil, heartrate: HeartrateStream? = nil, cadence: CadenceStream? = nil, watts: PowerStream? = nil, temp: TemperatureStream? = nil, moving: MovingStream? = nil, gradeSmooth: SmoothGradeStream? = nil) {
        self.time = time
        self.distance = distance
        self.latlng = latlng
        self.altitude = altitude
        self.velocitySmooth = velocitySmooth
        self.heartrate = heartrate
        self.cadence = cadence
        self.watts = watts
        self.temp = temp
        self.moving = moving
        self.gradeSmooth = gradeSmooth
    }

    public enum CodingKeys: String, CodingKey { 
        case time
        case distance
        case latlng
        case altitude
        case velocitySmooth = "velocity_smooth"
        case heartrate
        case cadence
        case watts
        case temp
        case moving
        case gradeSmooth = "grade_smooth"
    }

}
