//
// SummaryGear.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SummaryGear: Codable {

    /** The gear&#x27;s unique identifier. */
    public var _id: String?
    /** Resource state, indicates level of detail. Possible values: 2 -&gt; \&quot;summary\&quot;, 3 -&gt; \&quot;detail\&quot; */
    public var resourceState: Int?
    /** Whether this gear&#x27;s is the owner&#x27;s default one. */
    public var primary: Bool?
    /** The gear&#x27;s name. */
    public var name: String?
    /** The distance logged with this gear. */
    public var distance: Float?

    public init(_id: String? = nil, resourceState: Int? = nil, primary: Bool? = nil, name: String? = nil, distance: Float? = nil) {
        self._id = _id
        self.resourceState = resourceState
        self.primary = primary
        self.name = name
        self.distance = distance
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case resourceState = "resource_state"
        case primary
        case name
        case distance
    }

}
