//
// SummarySegmentEffort.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SummarySegmentEffort: Codable {

    /** The unique identifier of this effort */
    public var _id: Int64?
    /** The unique identifier of the activity related to this effort */
    public var activityId: Int64?
    /** The effort&#x27;s elapsed time */
    public var elapsedTime: Int?
    /** The time at which the effort was started. */
    public var startDate: Date?
    /** The time at which the effort was started in the local timezone. */
    public var startDateLocal: Date?
    /** The effort&#x27;s distance in meters */
    public var distance: Float?
    /** Whether this effort is the current best on the leaderboard */
    public var isKom: Bool?

    public init(_id: Int64? = nil, activityId: Int64? = nil, elapsedTime: Int? = nil, startDate: Date? = nil, startDateLocal: Date? = nil, distance: Float? = nil, isKom: Bool? = nil) {
        self._id = _id
        self.activityId = activityId
        self.elapsedTime = elapsedTime
        self.startDate = startDate
        self.startDateLocal = startDateLocal
        self.distance = distance
        self.isKom = isKom
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case activityId = "activity_id"
        case elapsedTime = "elapsed_time"
        case startDate = "start_date"
        case startDateLocal = "start_date_local"
        case distance
        case isKom = "is_kom"
    }

}
