//
// SummaryPRSegmentEffort.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SummaryPRSegmentEffort: Codable {

    /** The unique identifier of the activity related to the PR effort. */
    public var prActivityId: Int64?
    /** The elapsed time ot the PR effort. */
    public var prElapsedTime: Int?
    /** The time at which the PR effort was started. */
    public var prDate: Date?
    /** Number of efforts by the authenticated athlete on this segment. */
    public var effortCount: Int?

    public init(prActivityId: Int64? = nil, prElapsedTime: Int? = nil, prDate: Date? = nil, effortCount: Int? = nil) {
        self.prActivityId = prActivityId
        self.prElapsedTime = prElapsedTime
        self.prDate = prDate
        self.effortCount = effortCount
    }

    public enum CodingKeys: String, CodingKey { 
        case prActivityId = "pr_activity_id"
        case prElapsedTime = "pr_elapsed_time"
        case prDate = "pr_date"
        case effortCount = "effort_count"
    }

}
