//
// SummaryAthlete.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SummaryAthlete: Codable {

    public enum Sex: String, Codable { 
        case m = "M"
        case f = "F"
    }
    /** The unique identifier of the athlete */
    public var _id: Int64?
    /** Resource state, indicates level of detail. Possible values: 1 -&gt; \&quot;meta\&quot;, 2 -&gt; \&quot;summary\&quot;, 3 -&gt; \&quot;detail\&quot; */
    public var resourceState: Int?
    /** The athlete&#x27;s first name. */
    public var firstname: String?
    /** The athlete&#x27;s last name. */
    public var lastname: String?
    /** URL to a 62x62 pixel profile picture. */
    public var profileMedium: String?
    /** URL to a 124x124 pixel profile picture. */
    public var profile: String?
    /** The athlete&#x27;s city. */
    public var city: String?
    /** The athlete&#x27;s state or geographical region. */
    public var state: String?
    /** The athlete&#x27;s country. */
    public var country: String?
    /** The athlete&#x27;s sex. */
    public var sex: Sex?
    /** Deprecated.  Use summit field instead. Whether the athlete has any Summit subscription. */
    public var premium: Bool?
    /** Whether the athlete has any Summit subscription. */
    public var summit: Bool?
    /** The time at which the athlete was created. */
    public var createdAt: Date?
    /** The time at which the athlete was last updated. */
    public var updatedAt: Date?

    public init(_id: Int64? = nil, resourceState: Int? = nil, firstname: String? = nil, lastname: String? = nil, profileMedium: String? = nil, profile: String? = nil, city: String? = nil, state: String? = nil, country: String? = nil, sex: Sex? = nil, premium: Bool? = nil, summit: Bool? = nil, createdAt: Date? = nil, updatedAt: Date? = nil) {
        self._id = _id
        self.resourceState = resourceState
        self.firstname = firstname
        self.lastname = lastname
        self.profileMedium = profileMedium
        self.profile = profile
        self.city = city
        self.state = state
        self.country = country
        self.sex = sex
        self.premium = premium
        self.summit = summit
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case resourceState = "resource_state"
        case firstname
        case lastname
        case profileMedium = "profile_medium"
        case profile
        case city
        case state
        case country
        case sex
        case premium
        case summit
        case createdAt = "created_at"
        case updatedAt = "updated_at"
    }

}
