//
// TimedZoneDistribution.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Stores the exclusive ranges representing zones and the time spent in each. */
public typealias TimedZoneDistribution = [TimedZoneRange]