//
// UpdatableActivity.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct UpdatableActivity: Codable {

    /** Whether this activity is a commute */
    public var commute: Bool?
    /** Whether this activity was recorded on a training machine */
    public var trainer: Bool?
    /** Whether this activity is muted */
    public var hideFromHome: Bool?
    /** The description of the activity */
    public var _description: String?
    /** The name of the activity */
    public var name: String?
    public var type: ActivityType?
    public var sportType: SportType?
    /** Identifier for the gear associated with the activity. ‘none’ clears gear from activity */
    public var gearId: String?

    public init(commute: Bool? = nil, trainer: Bool? = nil, hideFromHome: Bool? = nil, _description: String? = nil, name: String? = nil, type: ActivityType? = nil, sportType: SportType? = nil, gearId: String? = nil) {
        self.commute = commute
        self.trainer = trainer
        self.hideFromHome = hideFromHome
        self._description = _description
        self.name = name
        self.type = type
        self.sportType = sportType
        self.gearId = gearId
    }

    public enum CodingKeys: String, CodingKey { 
        case commute
        case trainer
        case hideFromHome = "hide_from_home"
        case _description = "description"
        case name
        case type
        case sportType = "sport_type"
        case gearId = "gear_id"
    }

}
