//
// Zones.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Zones: Codable {

    public var heartRate: HeartRateZoneRanges?
    public var power: PowerZoneRanges?

    public init(heartRate: HeartRateZoneRanges? = nil, power: PowerZoneRanges? = nil) {
        self.heartRate = heartRate
        self.power = power
    }

    public enum CodingKeys: String, CodingKey { 
        case heartRate = "heart_rate"
        case power
    }

}
