//
// ZoneRange.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ZoneRange: Codable {

    /** The minimum value in the range. */
    public var min: Int?
    /** The maximum value in the range. */
    public var max: Int?

    public init(min: Int? = nil, max: Int? = nil) {
        self.min = min
        self.max = max
    }


}
